# Advanced operations with `pandas`

## Goals of this lecture

Previously, we discussed several basic operations we can performan with a [`pandas.DataFrame`](18-pandas).

In today's lecture, we'll cover more advanced operations:

- Filtering a `DataFrame` using a conditional statement.  
- Using `groupby` to aggregate across members of a category.  
- Identifying missing or `nan` values.

In [2]:
### Always remember to import the package!
import pandas as pd

## Review: reading in a `csv` file

`pandas.read_csv` takes in a **filepath** as an argument, and returns a `DataFrame`.

In [4]:
## Pass the filepath into pd.read_csv
df_pokemon = pd.read_csv("data/pokemon.csv")
df_pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

## Sorting a `DataFrame`

Often, we might find it useful to **sort** a `DataFrame` according to the values in a particular column.

### `sort_values`

- By default, `sort_values` will sort from *lowest* to *highest*.

In [8]:
df_pokemon.sort_values('HP').head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,236,1,90,45,30,30,40,3,False
55,50,Diglett,Ground,NaN,265,10,55,25,35,45,95,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
388,355,Duskull,Ghost,NaN,295,20,40,90,30,90,25,3,False
487,439,Mime Jr.,Psychic,Fairy,310,20,25,45,70,90,60,4,False

### `ascending = False`

We can change that with the `ascending` parameter.

In [10]:
df_pokemon.sort_values("HP", ascending = False).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
351,321,Wailord,Water,NaN,500,170,90,45,90,45,60,3,False
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False

## Basic descriptive statistics in `pandas`

> **Descriptive statistics** are ways to summarize and organize data.

- We've already covered [using `numpy` to calculate **descriptive statistics**](21-numpy-advanced).  
- But we can also use `pandas` in a very similar way!
   - (A *column* of a `DataFrame` is roughly analogous to a `numpy.ndarray`.)

### `describe`

The `describe` function gives you a bunch of handy descriptive statistics in a single call.

In [21]:
df_pokemon['Defense'].describe()

count    800.000000
mean      69.258750
std       25.534669
min        1.000000
25%       50.000000
50%       65.000000
75%       80.000000
max      255.000000
Name: HP, dtype: float64

In [19]:
print(df_pokemon['Defense'].describe()["mean"])
print(df_pokemon['Defense'].describe()["25%"])
print(df_pokemon['Defense'].describe()["50%"])

73.8425
50.0
70.0

### Table of qualitative variable

We cannot calculate the `mean` of the `Type 1` variable, because `Type 1` is a **qualitative** variable. But we can count how many of each *category* there are.

In [13]:
df_pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [15]:
df_pokemon['Type 1'].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

## Creating a new column

`pandas` also makes it relatively easy to make a new column.

Syntax:

```python
dataframe_name[new_column_name] = ...
```

In [20]:
### Setting the column to a single value 
### just duplicates that value throughout the column
df_pokemon['Trainer'] = 'Catarina'

In [21]:
df_pokemon.head(2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Stronger,Trainer
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,False,Catarina
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,False,Catarina

### Using an existing column to make a new column

You can also use values in an **existing** column to make a new column.

- Example: a new column called `Stronger` that denotes with a boolean whether a Pokemon has strength `=> 100`

In [16]:
df_pokemon['Stronger'] = df_pokemon['Attack'] >= 100

In [17]:
df_pokemon['Stronger'].value_counts(normalize = True)

Stronger
False    0.7375
True     0.2625
Name: proportion, dtype: float64

### Check-in

Create a new column of `df_pokemon` that calculates the **ratio** between the `Attack` of a Pokemon and its `Defense`.

In [42]:
### Your code here
df_pokemon['ratio'] = df_pokemon['Attack'] / df_pokemon['Defense']
df_pokemon.sort_values('ratio').tail()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Trainer,Stronger,ratio
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True,Umberto,True,3.000
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,Umberto,True,3.125
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,Umberto,True,3.750
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,Umberto,False,4.500
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,Umberto,True,9.000

### Making a new column with conditions on other columns

Create a new column `faster_attack` that denotes if the `Sp. Atk` is greater than `Sp. Def`.

In [23]:
df_pokemon['faster_attack'] = df_pokemon['Sp. Atk'] > df_pokemon['Sp. Def']
df_pokemon['Defense'].describe()

count    800.000000
mean      73.842500
std       31.183501
min        5.000000
25%       50.000000
50%       70.000000
75%       90.000000
max      230.000000
Name: Defense, dtype: float64

If we want to split our observations between three groups; 

- one for pokemon that attack faster than they defend;
- one for pokemon that attack and defend with same speed, and
- one for pokemon that defend faster than they attack;

we can code a categorical variable with numpy.

In [24]:
import numpy as np

conditions = [
    df_pokemon['Sp. Atk'] > df_pokemon['Sp. Def'],
    df_pokemon['Sp. Atk'] < df_pokemon['Sp. Def'],
    df_pokemon['Sp. Atk'] == df_pokemon['Sp. Def']
]

choices = ['Faster Attack', 'Faster Defense', 'Equal Attack and Defense Speed']

df_pokemon['faster_attack'] = np.select(conditions, choices)

df_pokemon['faster_attack'].describe()

count                800
unique                 3
top       Faster Defense
freq                 342
Name: faster_attack, dtype: object

In [25]:
df_pokemon['faster_attack'].value_counts()

faster_attack
Faster Defense                    342
Faster Attack                     338
Equal Attack and Defense Speed    120
Name: count, dtype: int64

## Filtering a `DataFrame`

Often, we want to **filter** a `DataFrame` so we only see observations that meet certain **conditions**.

- "Only show trials from the `Congruent` condition".  
- "Only show neighborhoods that are `NEAR BAY`." 
- "Only show scores below 70%."

Fundamentally, this is done by using a **conditional statement**.

### Refresher: conditionals

> In a nutshell, a **conditional** is a statement that checks for whether some *condition* is met.

We can use the `if` command to **control** which lines of code are executed.

In [43]:
def square_if_even(x):
    if x % 2 == 0:
        return x ** 2
    else:
        return x

In [46]:
square_if_even(10)

100

In [47]:
square_if_even(9)

9

### Conditionals and filtering

- **Filtering** a `DataFrame` is analogous to applying a *condition*.  
- I.e., "show me only the rows that meet *this condition*".

### Example 1: filtering on a boolean/categorical variable

- The `legendary` column is a *boolean* variable, meaning the values are true or false. This works similarly to categorical variables.

In [52]:
## How many legendary pokemon?
len(df_pokemon[df_pokemon['Legendary']==True])

65

In [57]:
## Compare to actual length of dataframe
len(df_pokemon)

len(df_pokemon[df_pokemon['Legendary']==True]) / len(df_pokemon)

df_pokemon['Legendary'].value_counts(normalize = True)

False    0.91875
True     0.08125
Name: Legendary, dtype: float64

### Example 2: filtering on a continuous variable

- The `HP` column is a *continuous* variable.
- Let's show only the rows for Pokemon with a `HP > 150`.

In [58]:
df_pokemon[df_pokemon['HP'] > 150]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Trainer,Stronger,ratio
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False,Umberto,False,1.000000
155,143,Snorlax,Normal,NaN,540,160,110,65,65,110,30,1,False,Umberto,True,1.692308
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False,Umberto,False,0.568966
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False,Umberto,False,1.000000
351,321,Wailord,Water,NaN,500,170,90,45,90,45,60,3,False,Umberto,False,2.000000
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False,Umberto,False,0.937500

In [59]:
## Compare to actual length of df_pokemon
len(df_pokemon)
len(df_pokemon[df_pokemon['HP'] > 150]) / len(df_pokemon)

0.0075

### Interim summary: filtering syntax

To filter a `DataFrame`, we can use the bracket (`[]`) syntax.:

```python
df_name[df_name['col_name']==CONDITION]
```

(Note that `==CONDITION` would be replaced with whatever **condition** you want to filter on.)

### Check-in

Write a statement to **filter** `df_pokemon` to show only the pokemon where `Attack` is greater than or equal to 50. 

- How many rows are in this subset?  
- What proportion of Pokemon meet this criteria?
- What is the mean `HP` in this subset?

In [29]:
### Your code here
print(len(df_pokemon[df_pokemon['Attack'] >= 50]))
print(len(df_pokemon[df_pokemon['Attack'] >= 50])/len(df_pokemon)*100)
print(df_pokemon[df_pokemon['Attack'] >= 50]['HP'].mean())

667
83.375
72.55472263868066

### Check-in

What is the mean `HP` of Pokemon that are `Legendary` vs. those that aren't?

**Hint**: Create *two* subset `DataFrame`s, filtering for `== True` and `!= False`.

In [64]:
### Your code here
print(df_pokemon[df_pokemon['Legendary'] == True]['HP'].mean())
print(df_pokemon[df_pokemon['Legendary'] == False]['HP'].mean())

92.73846153846154
67.18231292517007

### Interim summary

- We can apply **conditionals** to a `DataFrame` to *filter* that `DataFrame`.
   - "Show me only observations that meet some criteria."
- We also used this to look at the `mean` value of some column (`HP`) as a function of some other column (`Legendary`).
- But there's actually an even easier way to do this!

## Using `groupby`

> The [`groupby` function](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) allows you to **split data** (i.e., along different categories) then **apply** some function to each split of that data (e.g., `mean`).

Examples:

- Calculate the `mean` `HP` for each category in `Type 1`.
- Calculate the `sum` of `costs` for each `month`.

### Simple example

- Let's demo this in a simple `DataFrame`.
- First, we create a `DataFrame` with information about `Reaction Time` in two different `Condition`s.
- Are people faster or slower for `Congruent` vs. `Incongruent` conditions?
   - E.g., supppose these are results from the [Stroop task](https://en.wikipedia.org/wiki/Stroop_effect).

In [30]:
df_rt = pd.DataFrame({'Condition': ['Congruent', 'Congruent', 'Congruent',
                                    'Incongruent', 'Incongruent', 'Incongruent'],
                          'Reaction Time': [500, 460, 532, 730, 720, 670]})
df_rt

     Condition  Reaction Time
0    Congruent            500
1    Congruent            460
2    Congruent            532
3  Incongruent            730
4  Incongruent            720
5  Incongruent            670

#### Using `groupby`

To calculate the `mean` `Reaction Time` in each condition, use:

In [31]:
df_rt.groupby("Condition").mean()

             Reaction Time
Condition
Congruent       497.333333
Incongruent     706.666667

#### Using `groupby` and `describe`

To get more statistics about each condition, use `describe`:

In [69]:
df_rt.groupby("Condition").describe()

            Reaction Time                                                     \
                    count        mean        std    min    25%    50%    75%
Condition
Congruent             3.0  497.333333  36.073998  460.0  480.0  500.0  516.0
Incongruent           3.0  706.666667  32.145503  670.0  695.0  720.0  725.0


               max
Condition
Congruent    532.0
Incongruent  730.0

### Check-in

Use `groupby` to calculate the average `HP` for each category in `Legendary`. Which category has the highest average?

In [36]:
### Your code here
df_pokemon.groupby('Type 1')['HP'].describe().sort_values("mean").tail(1)

        count     mean        std   min   25%   50%     75%    max
Type 1
Dragon   32.0  83.3125  23.795415  41.0  67.5  80.0  101.25  125.0

## Missing data!

- In practice, **real-world** data is often messy.  
- This includes **missing values**, which take on the value/label `NaN`.
   - `NaN` = "Not a Number".
- [Dealing with `NaN` values is one of the main challenges in CSS!](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html)

### Where do missing values come from?

- Lots of reasons for [missing data](https://en.wikipedia.org/wiki/Missing_data)!
  - Experiment crashed, so some trials are missing.
  - Some people don't answer all questions on a survey.
  - Some people "drop" out of a longitudinal study.  

| Subject | Condition | RT |
| ------- | ---------- | --- | 
| 1     | Congruent        | 500 |
| 2     | Congruent      | 550 |
| 3     | Incongruent      | 670 |
| 4     | NaN      | NaN |

### Why does missing data matter?

Again, [lots of reasons](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3668100/):

1. If you're unaware of it, then you might be **overestimating** how many observations you have. (E.g., you think `N = 500`, but actually `N = 450`.)
2. If missing values are **non-randomly distributed**, your results might be **biased**. (E.g., maybe the `Placebo` group is more likely to drop out of a longitudinal study?)
3. Missing values may complicate your analysis.

### How to deal with missing data

- **Identify** missing values.  
- **Analyze** whether they're randomly or non-randomly distributed.  
- **Decide** how to handle them:
  - *Remove* any rows with missing data from all analyses?  
  - *Ignore* rows with missing data for *some* analyses but not all?  
  - Try to *impute* ("fill in") the missing data using other information?
- Not an easy problem!

### Identifying missing data

- The first step is **identifying** missing values.
- For this, you can use `isna`.
   - Returns a vector of `True`/`False` values indicating whether a given observation is `NaN`.

In [76]:
### This means none of those columns
### have NaN in top 5 rows
df_pokemon.isna().tail()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Trainer,Stronger,ratio
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
796,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
797,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
798,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
799,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

#### Which columns have `NaN`?

We can discover whether any column has `NaN` using `isna().any()`.

In [77]:
### Tells you which columns have NaN values
df_pokemon.isna().any()

#             False
Name          False
Type 1        False
Type 2         True
Total         False
HP            False
Attack        False
Defense       False
Sp. Atk       False
Sp. Def       False
Speed         False
Generation    False
Legendary     False
Trainer       False
Stronger      False
ratio         False
dtype: bool

#### Inspecting `Type 2`

In [78]:
### These rows have NaN for "total_bedrooms"
df_pokemon[df_pokemon['Type 2'].isna()].head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Trainer,Stronger,ratio
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Umberto,False,1.209302
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,Umberto,False,1.103448
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,Umberto,False,0.738462
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False,Umberto,False,0.787500
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False,Umberto,False,0.830000
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,Umberto,True,0.858333
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False,Umberto,False,0.857143
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False,Umberto,False,0.363636
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False,Umberto,False,1.600000
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False,Umberto,False,1.350000

In [79]:
len(df_pokemon[df_pokemon['Type 2'].isna()])

386

### `drop_na`

One approach is to **drop** these observations altogether. You can do this using `dropna(column_name)`.

In [80]:
df_pokemon_subset = df_pokemon.dropna(subset = "Type 2")
len(df_pokemon_subset)

414

In [81]:
### No more NaN
df_pokemon_subset.isna().any()

#             False
Name          False
Type 1        False
Type 2        False
Total         False
HP            False
Attack        False
Defense       False
Sp. Atk       False
Sp. Def       False
Speed         False
Generation    False
Legendary     False
Trainer       False
Stronger      False
ratio         False
dtype: bool

### Filtering on `~isna`

You can also **drop** observations by *filtering* on values that *aren't* `NaN`.

- The `~` syntax is a way to write `not` in `pandas` syntax.

In [ ]:
df_pokemon_subset = df_pokemon[~df_pokemon['Type 2'].isna()]
len(df_pokemon_subset)

In [ ]:
### No more NaN
df_pokemon_subset.isna().any()

### Do we *want* to remove `NaN`?

- In this particular case, removing `NaN` may not be necessary.
  - Lots of Pokemon just don't *have* a secondary Type. 
- But in other cases, `NaN` actually implies **missing data**, not just a feature of some observations.
- In those cases, we might want to remove those observations.

## Conclusion

This concludes our unit on `pandas`.

- `pandas` is central to data manipulation and data analysis in Python.  
- It's a handy way to read `.csv` files (`read_csv`).  
- As you'll see in CSS 2, `pandas` can also be used in conjunction with **visualization** and **analysis** packages.